### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by waywardmonkeys**
A bit of bringing things up to date.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@pyfisch While you're around (on the issues), any chance you could take a look at this and the other PRs, please?

**Comment by waywardmonkeys** [comment]
Those issues with clippy are fixed by #23.

**Comment by waywardmonkeys** [comment]
@pyfisch Thanks!

**Comment by pyfisch** [comment]
@waywardmonkeys You're welcome. I'll publish a new patch release with these changes to crates.io soon.

**Comment by waywardmonkeys** [comment]
@pyfisch Hold up on that ... now that these landed, I have a few more to submit. :)

**Pull request merged**
