### PR TITLE
Link to Working Draft instead of Editor’s Draft 

### PR DESCRIPTION
**Pull request by madsmtm**
Also update to the latest spec, which fixes a few spelling errors.

### CODE REVIEW

**Comment by pyfisch** [comment]
Why are you changing the links from one version of the document to another?

If I recall correctly implementors (mainly browsers) tend to use the version at https://w3c.github.io/
The terminology is a bit confusing but this document is also called a working draft:

grafik

**Comment by madsmtm** [comment]
I dunno what I was thinking when I wrote the title, but I think I meant ["Working Draft"](https://www.w3.org/standards/types/#WD) -> ["Proposed Recommendation"](https://www.w3.org/standards/types/#PR).

Because from my understanding, the proposed recommendation is the actual spec, the others are mostly just pre-releases of it (and that's why so many reference them, since that's the "canonical" place for them before the spec is standardized).

**Comment by pyfisch** [comment]
Lets keep the references to the draft at w3c.gitlab.io, as this is were relevant changes are first made. In the case of the W3C the publication as a "proposed recommendation" or standard is less relevant. (Not that I expect major changes to keyboard events.)

**Comment by madsmtm** [comment]
Sure!

**Pull request closed without merging**
