### PR TITLE
cargo fmt (on non-generated files)

### PR DESCRIPTION
**Pull request by waywardmonkeys**
I didn't update the generator to fix the (minor) issues in the generated files, so this is the non-generated file only.

### CODE REVIEW

**Comment by pyfisch** [comment]
Can you add `cargo fmt` to CI with this PR?

**Comment by waywardmonkeys** [comment]
> Can you add cargo fmt to CI with this PR?

Not without either fixing the formatting of `src/key.rs` and `src/code.rs` or getting `cargo fmt` to ignore them.

**Comment by pyfisch** [comment]
Resolved with #32

**Comment by waywardmonkeys** [comment]
Thanks!

**Pull request closed without merging**
